name: Just print the OS information
on:
  issues:
    types: [labeled]

jobs:
  do_the_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Execute `uname -a`
        run: uname -a

