name: Get all items
on:
  issues:
    types: [labeled]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: alwx/actions-test@master
        id: my_step_id
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          column_id: 8413302
          archived_state: all
          per_page: 100
          page: 1
          order: priority:important,priority:high,priority:medium,priority:low
      - name: Print outputs
        run: |
          echo "yay"
